# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [12.6]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        node --version
        npm --version
    
    - name: npm install
      run: npm ci

    - name: npm build
      run: npm run build

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.6.0'
      - name: Node version
        run: |
          node --version
          npm --version
      - name: Checkout codebase
        uses: actions/checkout@v1
        with:
          submodules: recursive
      
      - name: npm install
        run: npm ci

      - name: build linux
        id: build
        run: |
          npm run electron-pack
      - uses: actions/upload-artifact@v1
        name: Upload artifacts
        with:
          name: Linux
          path: ../artifacts/

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.6.0'

      - name: Node version
        run: |
          node --version
          npm --version
      - uses: actions/checkout@v2

      - name: npm install
        run: npm ci

      - name: build windows
        run: |
          npm run electron-pack

      - uses: actions/upload-artifact@v1
        name: Upload x64 artifacts
        with:
          name: AgWin
          path: ../artifacts/x64/
